version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram_db
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: foodgram_backend
    image: anarhist2023/foodgram_backend
    env_file: ../.env
    volumes:
      - ../static/:/app/static/colorfield/
      - ../backend/db.sqlite3:/app/db.sqlite3
      - ../static/:/app/static/
      - ../media/:/app/media/recipes/
  frontend:
    container_name: foodgram_frontend
    image: anarhist2023/foodgram_frontend
    env_file: ../.env
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    container_name: foodgram_nginx
    image: anarhist2023/foodgram_nginx
    env_file: ../.env
    ports:
      - "8000:80"
    volumes:
      - ../static/:/var/html/static/
      - ../static/:/var/html/static/colorfield/
      - ../media/:/var/html/media/recipes/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
