# Generated by Django 4.2.2 on 2023-06-26 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'verbose_name': 'Ингредиенты в рецепте'},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'verbose_name': ('Теги рецепта',)},
        ),
    ]
