# Generated by Django 4.2.2 on 2023-06-26 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_ingredientinrecipe_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999.999)], verbose_name='Количество'),
        ),
    ]
